# Generated by Django 5.0.6 on 2024-06-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_query', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=120)),
                ('federal_district', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=120)),
                ('area', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('city_district', models.CharField(max_length=120)),
                ('settlement', models.CharField(max_length=120)),
                ('street', models.CharField(max_length=120)),
                ('stead', models.CharField(max_length=50)),
                ('house', models.CharField(max_length=50)),
                ('block', models.CharField(max_length=50)),
                ('entrance', models.CharField(max_length=10)),
                ('floor', models.CharField(max_length=10)),
                ('flat', models.CharField(max_length=50)),
                ('geo_lat', models.FloatField()),
                ('geo_lon', models.FloatField()),
            ],
        ),
    ]
