# Generated by Django 5.0.6 on 2024-06-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_address_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='raw_query',
            new_name='source',
        ),
    ]
