# Generated by Django 5.0.6 on 2024-06-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_rename_raw_query_address_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='area',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='block',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city_district',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='entrance',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='federal_district',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='flat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='settlement',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='stead',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
