# Generated by Django 5.0.6 on 2024-06-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_address_unique_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='street_type_full',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
