# Generated by Django 5.0.6 on 2024-06-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_address_street_type_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
